Repository OCA/stock-logistics-transport, pull requests merged in 2021-12, with the labels that each got.

#68 [13.0][FIX] shipment_advice: lock transfers during validation
  shipment_advice/models/shipment_advice.py
Labels: bug, approved, bot is merging ⏳

#65 [14.0][IMP] shipment_advice: test with normal stock user, increase coverage
  shipment_advice/models/shipment_advice.py
  shipment_advice/models/stock_move_line.py
  shipment_advice/models/stock_package_level.py
  shipment_advice/models/stock_picking.py
  shipment_advice/readme/CONTRIBUTORS.rst
  shipment_advice/tests/__init__.py
  shipment_advice/tests/common.py
  shipment_advice/tests/test_shipment_advice_load.py
  shipment_advice/tests/test_shipment_advice_stock_user.py
  shipment_advice/wizards/load_shipment.py
  shipment_advice/wizards/plan_shipment.py
Labels: approved, ready to merge, bot is merging ⏳

#70 [13.0][FIX] shipment_advice: filter on current warehouse when listing deliveries to load
  shipment_advice/models/shipment_advice.py
Labels: bug, bot is merging ⏳

#72 [MIG][14.0] stock_location_address
  setup/stock_location_address/odoo/addons/stock_location_address
  setup/stock_location_address/setup.py
  stock_location_address/README.rst
  stock_location_address/__init__.py
  stock_location_address/__manifest__.py
  stock_location_address/i18n/stock_location_address.pot
  stock_location_address/models/__init__.py
  stock_location_address/models/stock_location.py
  stock_location_address/readme/CONTRIBUTORS.rst
  stock_location_address/readme/DESCRIPTION.rst
  stock_location_address/readme/USAGE.rst
  stock_location_address/static/description/icon.png
  stock_location_address/tests/__init__.py
  stock_location_address/tests/test_location_address.py
  stock_location_address/views/stock_location_views.xml
Labels: approved, bot is merging ⏳

#73 [14.0][MIG] stock_location_address_purchase
  setup/stock_location_address_purchase/odoo/addons/stock_location_address_purchase
  setup/stock_location_address_purchase/setup.py
  stock_location_address_purchase/README.rst
  stock_location_address_purchase/__init__.py
  stock_location_address_purchase/__manifest__.py
  stock_location_address_purchase/i18n/stock_location_address_purchase.pot
  stock_location_address_purchase/models/__init__.py
  stock_location_address_purchase/models/purchase.py
  stock_location_address_purchase/models/stock_rule.py
  stock_location_address_purchase/static/description/icon.png
  stock_location_address_purchase/tests/__init__.py
  stock_location_address_purchase/tests/test_purchase_address.py
  stock_location_address_purchase/tests/test_purchase_buy_rule.py
Labels: approved, bot is merging ⏳

#74 [15.0][MIG] stock_location_address
  setup/stock_location_address/odoo/addons/stock_location_address
  setup/stock_location_address/setup.py
  stock_location_address/README.rst
  stock_location_address/__init__.py
  stock_location_address/__manifest__.py
  stock_location_address/i18n/stock_location_address.pot
  stock_location_address/models/__init__.py
  stock_location_address/models/stock_location.py
  stock_location_address/readme/CONTRIBUTORS.rst
  stock_location_address/readme/DESCRIPTION.rst
  stock_location_address/readme/USAGE.rst
  stock_location_address/static/description/icon.png
  stock_location_address/static/description/index.html
  stock_location_address/tests/__init__.py
  stock_location_address/tests/test_location_address.py
  stock_location_address/views/stock_location_views.xml
Labels: approved, bot is merging ⏳
