Repository OCA/stock-logistics-transport, pull requests merged in 2021-09, with the labels that each got.

#62 [13.0][IMP] shipment_advice: add hook to filter packages to list
  shipment_advice/models/shipment_advice.py
Labels: bot is merging ⏳

#63 [MIG] stock_dock: Migration to 14.0
  setup/stock_dock/odoo/addons/stock_dock
  setup/stock_dock/setup.py
  stock_dock/README.rst
  stock_dock/__init__.py
  stock_dock/__manifest__.py
  stock_dock/demo/stock_dock.xml
  stock_dock/i18n/stock_dock.pot
  stock_dock/models/__init__.py
  stock_dock/models/stock_dock.py
  stock_dock/readme/CONTRIBUTORS.rst
  stock_dock/readme/CREDITS.rst
  stock_dock/readme/DESCRIPTION.rst
  stock_dock/security/ir.model.access.csv
  stock_dock/static/description/icon.png
  stock_dock/static/description/index.html
  stock_dock/views/stock_dock.xml
Labels: approved, migration, bot is merging ⏳

#64 [MIG] shipment_advice: Migration to 14.0
  setup/shipment_advice/odoo/addons/shipment_advice
  setup/shipment_advice/setup.py
  shipment_advice/README.rst
  shipment_advice/__init__.py
  shipment_advice/__manifest__.py
  shipment_advice/data/ir_sequence.xml
  shipment_advice/demo/stock_dock.xml
  shipment_advice/i18n/shipment_advice.pot
  shipment_advice/models/__init__.py
  shipment_advice/models/res_company.py
  shipment_advice/models/res_config_settings.py
  shipment_advice/models/shipment_advice.py
  shipment_advice/models/stock_move.py
  shipment_advice/models/stock_move_line.py
  shipment_advice/models/stock_package_level.py
  shipment_advice/models/stock_picking.py
  shipment_advice/readme/CONTRIBUTORS.rst
  shipment_advice/readme/CREDITS.rst
  shipment_advice/readme/DESCRIPTION.rst
  shipment_advice/report/report_shipment_advice.xml
  shipment_advice/report/reports.xml
  shipment_advice/security/ir.model.access.csv
  shipment_advice/static/description/icon.png
  shipment_advice/static/description/index.html
  shipment_advice/tests/__init__.py
  shipment_advice/tests/common.py
  shipment_advice/tests/test_shipment_advice.py
  shipment_advice/tests/test_shipment_advice_load.py
  shipment_advice/tests/test_shipment_advice_plan.py
  shipment_advice/tests/test_shipment_advice_unload.py
  shipment_advice/views/res_config_settings.xml
  shipment_advice/views/shipment_advice.xml
  shipment_advice/views/stock_move.xml
  shipment_advice/views/stock_move_line.xml
  shipment_advice/views/stock_package_level.xml
  shipment_advice/views/stock_picking.xml
  shipment_advice/wizards/__init__.py
  shipment_advice/wizards/load_shipment.py
  shipment_advice/wizards/load_shipment.xml
  shipment_advice/wizards/plan_shipment.py
  shipment_advice/wizards/plan_shipment.xml
  shipment_advice/wizards/unload_shipment.py
  shipment_advice/wizards/unload_shipment.xml
  shipment_advice/wizards/unplan_shipment.py
  shipment_advice/wizards/unplan_shipment.xml
Labels: approved, bot is merging ⏳
