Repository OCA/stock-logistics-transport, pull requests merged in 2022-01, with the labels that each got.

#75 [15.0][MIG] stock_location_address_purchase
  setup/stock_location_address_purchase/odoo/addons/stock_location_address_purchase
  setup/stock_location_address_purchase/setup.py
  stock_location_address_purchase/README.rst
  stock_location_address_purchase/__init__.py
  stock_location_address_purchase/__manifest__.py
  stock_location_address_purchase/i18n/stock_location_address_purchase.pot
  stock_location_address_purchase/models/__init__.py
  stock_location_address_purchase/models/purchase.py
  stock_location_address_purchase/models/stock_rule.py
  stock_location_address_purchase/static/description/icon.png
  stock_location_address_purchase/tests/__init__.py
  stock_location_address_purchase/tests/test_purchase_address.py
  stock_location_address_purchase/tests/test_purchase_buy_rule.py
Labels: approved, bot is merging ⏳

#69 [14.0][FW] shipment_advice: multiple ports from 13.0
  shipment_advice/models/shipment_advice.py
Labels: bug, bot is merging ⏳

#76 [13.0][IMP] shipment_advice: handle multi warehouses
  shipment_advice/models/shipment_advice.py
  shipment_advice/views/shipment_advice.xml
  stock_dock/models/stock_dock.py
  stock_dock/views/stock_dock.xml
Labels: enhancement, approved, bot is merging ⏳

#77 [14.0][FW] [13.0][IMP] shipment_advice: handle multi warehouses
  shipment_advice/models/shipment_advice.py
  shipment_advice/views/shipment_advice.xml
  stock_dock/models/stock_dock.py
  stock_dock/views/stock_dock.xml
Labels: bot is merging ⏳

#80 [14.0][FIX] shipment_advice: moves widget
  shipment_advice/views/shipment_advice.xml
Labels: bug, approved
