Repository OCA/stock-logistics-transport, pull requests merged in 2023-07, with the labels that each got.

#98 [IMP] shipment_advice: Use correct field for package type in report
  shipment_advice/report/report_shipment_advice.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#101 [16.0][FIX] shipment_advice: Use correct filters
  shipment_advice/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#102 [FIX] - don't copy shipment advice when duplicating a stock move
  shipment_advice/models/stock_move.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#103 [16.0][FIX] - shipment_advice: Unplan moves that were not loaded and validated
  shipment_advice/models/shipment_advice.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳
