Repository OCA/stock-logistics-transport, pull requests merged in 2024-10, with the labels that each got.

#139 [14.0][IMP] shipment_advice: Unplan planned moves for incoming
  shipment_advice/models/shipment_advice.py
  shipment_advice_bill_auto_complete/models/shipment_advice.py
Labels: approved, ready to merge, bot is merging ⏳

#131 [ADD] stock_depot
  setup/stock_depot/odoo/addons/stock_depot
  setup/stock_depot/setup.py
  stock_depot/README.rst
  stock_depot/__init__.py
  stock_depot/__manifest__.py
  stock_depot/models/__init__.py
  stock_depot/models/stock_depot.py
  stock_depot/readme/CONTRIBUTORS.rst
  stock_depot/readme/DESCRIPTION.rst
  stock_depot/security/ir.model.access.csv
  stock_depot/static/description/index.html
  stock_depot/views/stock_depot.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#144 [16.0] shipment_advice_planner_toursolver: Makes default delivery window optional
  shipment_advice_planner_toursolver/__manifest__.py
  shipment_advice_planner_toursolver/demo/toursolver_backend.xml
  shipment_advice_planner_toursolver/i18n/es.po
  shipment_advice_planner_toursolver/i18n/fr.po
  shipment_advice_planner_toursolver/i18n/it.po
  shipment_advice_planner_toursolver/i18n/shipment_advice_planner_toursolver.pot
  shipment_advice_planner_toursolver/migrations/16.0.3.0.0/pre-migrate.py
  shipment_advice_planner_toursolver/migrations/16.0.3.0.1/pre-migrate.py
  shipment_advice_planner_toursolver/models/__init__.py
  shipment_advice_planner_toursolver/models/toursolver_backend.py
  shipment_advice_planner_toursolver/models/toursolver_backend_option_definition.py
  shipment_advice_planner_toursolver/models/toursolver_request_props_definition.py
  shipment_advice_planner_toursolver/models/toursolver_task.py
  shipment_advice_planner_toursolver/security/toursolver_request_props_definition.xml
  shipment_advice_planner_toursolver/tests/__init__.py
  shipment_advice_planner_toursolver/tests/test_toursolver_request_props.py
  shipment_advice_planner_toursolver/views/toursolver_backend.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳

#125 [14.0][IMP] shipment_advice_bill_auto_complete: add info in chatter
  shipment_advice_bill_auto_complete/models/account_move.py
Labels: bot is merging ⏳

#136 [17.0][ADD] tms_product
  tms_product/README.rst
  tms_product/__init__.py
  tms_product/__manifest__.py
  tms_product/models/__init__.py
  tms_product/models/fleet_vehicle.py
  tms_product/models/product_template.py
  tms_product/models/stock_lot.py
  tms_product/models/stock_move.py
  tms_product/models/stock_picking.py
  tms_product/models/transportable_product.py
  tms_product/pyproject.toml
  tms_product/readme/CONTRIBUTORS.md
  tms_product/readme/CREDITS.md
  tms_product/readme/DESCRIPTION.md
  tms_product/readme/MAINTAINERS.md
  tms_product/readme/USAGE.md
  tms_product/security/ir.model.access.csv
  tms_product/static/description/icon.png
  tms_product/static/description/icon.svg
  tms_product/static/description/index.html
  tms_product/views/fleet_vehicle_views.xml
  tms_product/views/product_template_views.xml
  tms_product/views/stock_lot_views.xml
  tms_product/views/stock_picking_views.xml
  tms_product/views/transportable_product_views.xml
Labels: enhancement, needs review, bot is merging ⏳

#138 [17.0] [ADD] tms_account_asset
  tms_account_asset/README.rst
  tms_account_asset/__init__.py
  tms_account_asset/__manifest__.py
  tms_account_asset/models/__init__.py
  tms_account_asset/models/account_asset.py
  tms_account_asset/models/account_asset_profile.py
  tms_account_asset/models/account_move.py
  tms_account_asset/models/fleet_vehicle.py
  tms_account_asset/models/fleet_vehicle_model_category.py
  tms_account_asset/pyproject.toml
  tms_account_asset/readme/CONFIGURE.md
  tms_account_asset/readme/CONTRIBUTORS.md
  tms_account_asset/readme/CREDITS.md
  tms_account_asset/readme/DESCRIPTION.md
  tms_account_asset/readme/INSTALL.md
  tms_account_asset/readme/MAINTAINERS.md
  tms_account_asset/readme/USAGE.md
  tms_account_asset/static/description/icon.png
  tms_account_asset/static/description/icon.svg
  tms_account_asset/static/description/index.html
  tms_account_asset/views/account_asset_profile_views.xml
  tms_account_asset/views/account_asset_views.xml
  tms_account_asset/views/fleet_vehicle_model_category_views.xml
  tms_account_asset/views/fleet_vehicle_views.xml
Labels: enhancement, needs review, bot is merging ⏳

#135 [17.0][ADD] tms_purchase
  tms_purchase/README.rst
  tms_purchase/__init__.py
  tms_purchase/__manifest__.py
  tms_purchase/models/__init__.py
  tms_purchase/models/fleet_vehicle.py
  tms_purchase/models/purchase_order.py
  tms_purchase/models/stock_move.py
  tms_purchase/models/tms_order.py
  tms_purchase/pyproject.toml
  tms_purchase/readme/CONTRIBUTORS.md
  tms_purchase/readme/CREDITS.md
  tms_purchase/readme/DESCRIPTION.md
  tms_purchase/readme/INSTALL.md
  tms_purchase/readme/MAINTAINERS.md
  tms_purchase/readme/USAGE.md
  tms_purchase/static/description/icon.png
  tms_purchase/static/description/icon.svg
  tms_purchase/static/description/index.html
  tms_purchase/views/fleet_vehicle_views.xml
  tms_purchase/views/purchase_order_views.xml
  tms_purchase/views/tms_order.xml
Labels: enhancement, needs review, bot is merging ⏳

#148 [18.0][MIG] tms
  tms/README.rst
  tms/__init__.py
  tms/__manifest__.py
  tms/data/ir_sequence_data.xml
  tms/data/module_category.xml
  tms/data/tms_stage.xml
  tms/data/tms_team.xml
  tms/data/uom_category.xml
  tms/demo/res_partner.xml
  tms/demo/tms_crew.xml
  tms/demo/tms_driver.xml
  tms/demo/tms_order.xml
  tms/demo/tms_route.xml
  tms/demo/tms_team.xml
  tms/i18n/tms.pot
  tms/models/__init__.py
  tms/models/fleet_vehicle.py
  tms/models/res_config_settings.py
  tms/models/res_partner.py
  tms/models/tms_crew.py
  tms/models/tms_driver.py
  tms/models/tms_insurance.py
  tms/models/tms_order.py
  tms/models/tms_route.py
  tms/models/tms_stage.py
  tms/models/tms_team.py
  tms/pyproject.toml
  tms/readme/CONFIGURE.md
  tms/readme/CONTRIBUTORS.md
  tms/readme/CREDITS.md
  tms/readme/DESCRIPTION.md
  tms/readme/MAINTAINERS.md
  tms/readme/USAGE.md
  tms/security/ir.model.access.csv
  tms/security/ir_rule.xml
  tms/security/res_groups.xml
  tms/static/description/icon.png
  tms/static/description/icon.svg
  tms/static/description/index.html
  tms/tests/__init__.py
  tms/tests/test_fleet_vehicle.py
  tms/tests/test_res_partner.py
  tms/tests/test_tms_crew.py
  tms/tests/test_tms_driver.py
  tms/tests/test_tms_order.py
  tms/tests/test_tms_route.py
  tms/tests/test_tms_stage.py
  tms/tests/test_tms_team.py
  tms/views/fleet_menu.xml
  tms/views/fleet_vehicle.xml
  tms/views/menu.xml
  tms/views/res_config_settings.xml
  tms/views/res_partner.xml
  tms/views/tms_crew.xml
  tms/views/tms_driver.xml
  tms/views/tms_insurance.xml
  tms/views/tms_order.xml
  tms/views/tms_route.xml
  tms/views/tms_stage.xml
  tms/views/tms_team.xml
Labels: needs fixing, needs review, migration, bot is merging ⏳

#134 [ADD][17.0] tms_sale
  .eslintrc.yml
  tms_sale/README.rst
  tms_sale/__init__.py
  tms_sale/__manifest__.py
  tms_sale/models/__init__.py
  tms_sale/models/sale_order.py
  tms_sale/models/sale_order_line.py
  tms_sale/models/seat_ticket.py
  tms_sale/models/tms_order.py
  tms_sale/pyproject.toml
  tms_sale/security/ir.model.access.csv
  tms_sale/static/description/icon.png
  tms_sale/static/description/icon.svg
  tms_sale/static/src/js/line_ticket_wizard_controller.js
  tms_sale/static/src/js/line_trip_wizard_controller.js
  tms_sale/static/src/js/sale_order_line_product_field.js
  tms_sale/views/product_template_views.xml
  tms_sale/views/sale_order_views.xml
  tms_sale/views/seat_ticket_views.xml
  tms_sale/views/tms_order_views.xml
  tms_sale/wizard/__init__.py
  tms_sale/wizard/sale_order_line_trip.py
  tms_sale/wizard/sale_order_line_trip_views.xml
  tms_sale/wizard/seat_ticket_line.py
  tms_sale/wizard/seat_ticket_line_views.xml
Labels: enhancement, needs review, bot is merging ⏳

#133 [17.0][ADD] tms_expense
  tms_expense/README.rst
  tms_expense/__init__.py
  tms_expense/__manifest__.py
  tms_expense/data/hr_employee_driver.xml
  tms_expense/data/hr_expense_data.xml
  tms_expense/models/__init__.py
  tms_expense/models/hr_expense.py
  tms_expense/models/tms_driver.py
  tms_expense/models/tms_order.py
  tms_expense/pyproject.toml
  tms_expense/readme/CONTRIBUTORS.md
  tms_expense/readme/CREDITS.md
  tms_expense/readme/DESCRIPTION.md
  tms_expense/readme/INSTALL.md
  tms_expense/readme/MANTAINERS.md
  tms_expense/readme/USAGE.md
  tms_expense/static/description/icon.png
  tms_expense/static/description/icon.svg
  tms_expense/static/description/index.html
  tms_expense/views/hr_employee.xml
  tms_expense/views/hr_expense_views.xml
  tms_expense/views/tms_order.xml
Labels: enhancement, needs fixing, needs review, bot is merging ⏳

#137 [17.0][ADD] tms_account
  tms_account/README.rst
  tms_account/__init__.py
  tms_account/__manifest__.py
  tms_account/data/analytic_plan.xml
  tms_account/models/__init__.py
  tms_account/models/account_analytic_line.py
  tms_account/models/account_analytic_plan.py
  tms_account/models/account_move.py
  tms_account/models/account_move_line.py
  tms_account/models/analytic_account.py
  tms_account/models/hr_expense.py
  tms_account/models/purchase_order_line.py
  tms_account/models/res_config_settings.py
  tms_account/models/sale_order.py
  tms_account/models/sale_order_line.py
  tms_account/models/tms_order.py
  tms_account/models/tms_route.py
  tms_account/pyproject.toml
  tms_account/readme/CONFIGURE.md
  tms_account/readme/CONTRIBUTORS.md
  tms_account/readme/CREDITS.md
  tms_account/readme/DESCRIPTION.md
  tms_account/readme/INSTALL.md
  tms_account/readme/MAINTAINERS.md
  tms_account/readme/USAGE.md
  tms_account/security/res_groups.xml
  tms_account/static/description/icon.png
  tms_account/static/description/icon.svg
  tms_account/static/description/index.html
  tms_account/views/account_analytic_plan.xml
  tms_account/views/account_move.xml
  tms_account/views/res_config_settings.xml
  tms_account/views/tms_order.xml
  tms_account/views/tms_route.xml
Labels: enhancement, needs review, bot is merging ⏳
