Repository OCA/stock-logistics-transport, pull requests merged in 2024-11, with the labels that each got.

#150 [16.0][IMP] shipment_advice_planner_toursolver: Recreate toursolver task
  shipment_advice_planner_toursolver/models/shipment_advice.py
  shipment_advice_planner_toursolver/tests/cassettes/TestShipmentAdvicePlannerToursolver.test_recreate_task.yaml
  shipment_advice_planner_toursolver/tests/test_shipment_advice_planner_toursolver.py
  shipment_advice_planner_toursolver/views/shipment_advice.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#152 [IMP] tms: Model description and views
  tms/models/tms_driver.py
  tms/models/tms_insurance.py
  tms/views/res_config_settings.xml
Labels: bug, enhancement, needs review, bot is merging ⏳

#151 [16.0][FW] shipment_advice: multiple ports from 14.0
  shipment_advice/models/res_company.py
  shipment_advice/models/res_config_settings.py
  shipment_advice/models/shipment_advice.py
  shipment_advice/models/stock_move.py
  shipment_advice/models/stock_picking.py
  shipment_advice/readme/CONTRIBUTORS.rst
  shipment_advice/tests/__init__.py
  shipment_advice/tests/common.py
  shipment_advice/tests/test_shipment_advice.py
  shipment_advice/tests/test_shipment_advice_async.py
  shipment_advice/tests/test_shipment_advice_auto_close.py
  shipment_advice/tests/test_shipment_advice_load.py
  shipment_advice/tests/test_shipment_advice_picking_values.py
  shipment_advice/tests/test_shipment_advice_plan.py
  shipment_advice/tests/test_shipment_advice_stock_user.py
  shipment_advice/tests/test_shipment_advice_unload.py
  shipment_advice/views/res_config_settings.xml
  shipment_advice/views/shipment_advice.xml
  shipment_advice/views/stock_picking.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#154 [16.0][IMP] shipment_advice_planner: db column clean up
  shipment_advice_planner/__init__.py
  shipment_advice_planner/__manifest__.py
  shipment_advice_planner/hooks.py
  shipment_advice_planner/models/stock_picking.py
  shipment_advice_planner/static/description/index.html
Labels: approved, bot is merging ⏳

#149 [16.0][IMP] Add default filter to loaded_move_line_without_package_ids
  shipment_advice/views/shipment_advice.xml
Labels: approved, ready to merge, bot is merging ⏳
