Repository OCA/stock-logistics-transport, pull requests merged in 2024-09, with the labels that each got.

#141 [16.0][IMP] shipment_advice_planner_toursolver: Collect statistics
  shipment_advice_planner_toursolver/__manifest__.py
  shipment_advice_planner_toursolver/models/shipment_advice.py
  shipment_advice_planner_toursolver/models/toursolver_backend.py
  shipment_advice_planner_toursolver/models/toursolver_task.py
  shipment_advice_planner_toursolver/static/description/index.html
  shipment_advice_planner_toursolver/tests/cassettes/TestShipmentAdvicePlannerToursolver.test_cron_sync_task.yaml
  shipment_advice_planner_toursolver/tests/cassettes/TestShipmentAdvicePlannerToursolver.test_get_result_ko.yaml
  shipment_advice_planner_toursolver/tests/cassettes/TestShipmentAdvicePlannerToursolver.test_get_result_ok.yaml
  shipment_advice_planner_toursolver/tests/test_shipment_advice_planner_toursolver.py
  shipment_advice_planner_toursolver/views/shipment_advice.xml
  shipment_advice_planner_toursolver/views/toursolver_backend.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#146 [16.0] shipment_advice: multi-company support
  shipment_advice/models/shipment_advice.py
Labels: approved, ready to merge, bot is merging ⏳

#145 [ADD] tms
  tms/README.rst
  tms/__init__.py
  tms/__manifest__.py
  tms/data/ir_sequence_data.xml
  tms/data/module_category.xml
  tms/data/tms_stage.xml
  tms/data/tms_team.xml
  tms/data/uom_category.xml
  tms/demo/res_partner.xml
  tms/demo/tms_crew.xml
  tms/demo/tms_driver.xml
  tms/demo/tms_order.xml
  tms/demo/tms_route.xml
  tms/demo/tms_team.xml
  tms/i18n/tms.pot
  tms/models/__init__.py
  tms/models/fleet_vehicle.py
  tms/models/res_config_settings.py
  tms/models/res_partner.py
  tms/models/tms_crew.py
  tms/models/tms_driver.py
  tms/models/tms_insurance.py
  tms/models/tms_order.py
  tms/models/tms_route.py
  tms/models/tms_stage.py
  tms/models/tms_team.py
  tms/pyproject.toml
  tms/readme/CONFIGURE.md
  tms/readme/CONTRIBUTORS.md
  tms/readme/CREDITS.md
  tms/readme/DESCRIPTION.md
  tms/readme/MAINTAINERS.md
  tms/readme/USAGE.md
  tms/security/ir.model.access.csv
  tms/security/ir_rule.xml
  tms/security/res_groups.xml
  tms/static/description/icon.png
  tms/static/description/icon.svg
  tms/static/description/index.html
  tms/tests/__init__.py
  tms/tests/test_fleet_vehicle.py
  tms/tests/test_res_partner.py
  tms/tests/test_tms_crew.py
  tms/tests/test_tms_driver.py
  tms/tests/test_tms_order.py
  tms/tests/test_tms_route.py
  tms/tests/test_tms_stage.py
  tms/tests/test_tms_team.py
  tms/views/fleet_menu.xml
  tms/views/fleet_vehicle.xml
  tms/views/menu.xml
  tms/views/res_config_settings.xml
  tms/views/res_partner.xml
  tms/views/tms_crew.xml
  tms/views/tms_driver.xml
  tms/views/tms_insurance.xml
  tms/views/tms_order.xml
  tms/views/tms_route.xml
  tms/views/tms_stage.xml
  tms/views/tms_team.xml
Labels: enhancement, needs review, bot is merging ⏳
