Repository OCA/stock-logistics-transport, pull requests merged in 2025-01, with the labels that each got.

#159 [16.0][FIX] shipment_advice: validate picking
  shipment_advice/models/shipment_advice.py
  shipment_advice/readme/CONTRIBUTORS.rst
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#164 [18.0][FIX] tms: 'kanban-box' and duplicate label of 2 field
  tms/models/res_config_settings.py
  tms/views/res_config_settings.xml
  tms/views/tms_crew.xml
  tms/views/tms_driver.xml
  tms/views/tms_order.xml
  tms/views/tms_team.xml
Labels: bug, needs review, bot is merging ⏳

#162 [16.0][MIG] stock_location_address: migration to 16.0
  setup/stock_location_address/odoo/addons/stock_location_address
  setup/stock_location_address/setup.py
  stock_location_address/README.rst
  stock_location_address/__init__.py
  stock_location_address/__manifest__.py
  stock_location_address/i18n/stock_location_address.pot
  stock_location_address/models/__init__.py
  stock_location_address/models/stock_location.py
  stock_location_address/readme/CONTRIBUTORS.rst
  stock_location_address/readme/DESCRIPTION.rst
  stock_location_address/readme/USAGE.rst
  stock_location_address/static/description/icon.png
  stock_location_address/static/description/index.html
  stock_location_address/tests/__init__.py
  stock_location_address/tests/test_location_address.py
  stock_location_address/views/stock_location_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
