Repository OCA/stock-logistics-transport, pull requests merged in 2025-08, with the labels that each got.

#176 [18.0][MIG] stock_location_address: Migration to 18.0
  stock_location_address/README.rst
  stock_location_address/__init__.py
  stock_location_address/__manifest__.py
  stock_location_address/i18n/it.po
  stock_location_address/i18n/stock_location_address.pot
  stock_location_address/models/__init__.py
  stock_location_address/models/stock_location.py
  stock_location_address/pyproject.toml
  stock_location_address/readme/CONTRIBUTORS.md
  stock_location_address/readme/DESCRIPTION.md
  stock_location_address/readme/USAGE.md
  stock_location_address/static/description/icon.png
  stock_location_address/static/description/index.html
  stock_location_address/tests/__init__.py
  stock_location_address/tests/test_location_address.py
  stock_location_address/views/stock_location_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#187 [18.0][ADD] printing_auto_shipment_advice
  printing_auto_shipment_advice/README.rst
  printing_auto_shipment_advice/__init__.py
  printing_auto_shipment_advice/__manifest__.py
  printing_auto_shipment_advice/models/__init__.py
  printing_auto_shipment_advice/models/shipment_advice.py
  printing_auto_shipment_advice/models/stock_warehouse.py
  printing_auto_shipment_advice/pyproject.toml
  printing_auto_shipment_advice/readme/CONFIGURE.md
  printing_auto_shipment_advice/readme/CONTRIBUTORS.md
  printing_auto_shipment_advice/readme/DESCRIPTION.md
  printing_auto_shipment_advice/security/ir_rule.xml
  printing_auto_shipment_advice/static/description/icon.png
  printing_auto_shipment_advice/static/description/index.html
  printing_auto_shipment_advice/tests/__init__.py
  printing_auto_shipment_advice/tests/test_printing_auto_shipment_advice.py
  printing_auto_shipment_advice/views/shipment_advice.xml
  printing_auto_shipment_advice/views/stock_warehouse.xml
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#174 [16.0][IMP] shipment_advice Typos
  shipment_advice/i18n/es.po
  shipment_advice/i18n/fr.po
  shipment_advice/i18n/it.po
  shipment_advice/i18n/nl.po
  shipment_advice/i18n/shipment_advice.pot
  shipment_advice/models/shipment_advice.py
  shipment_advice/models/stock_move_line.py
  shipment_advice/views/res_config_settings.xml
Labels: bot is merging ⏳, stale

#192 [18.0][FIX] printing_auto_shipment_advice: change model on security rule
  printing_auto_shipment_advice/security/ir_rule.xml
Labels: bot is merging ⏳
